<?xml version='1.0' encoding='utf-8'?>
<testsuites>
  <properties>
    <property name="polarion-create-defects" value="false" />
    <property name="polarion-custom-lookup-method-field-id" value="testCaseID" />
    <property name="polarion-dry-run" value="false" />
    <property name="polarion-include-skipped" value="true" />
    <property name="polarion-lookup-method" value="custom" />
    <property name="polarion-project-id" value="not-set" />
    <property name="polarion-testrun-id" value="test-run-id" />
    <property name="polarion-testrun-status-id" value="finished" />
    <property name="polarion-user-id" value="not-set" />
  </properties>
  <testsuite errors="1" failures="0" skipped="0" tests="1" time="0.00020258699987607542">
    <testcase file="test_polarion.py" line="6" name="test_polarion" time="0.00020258699987607542">
      <error message="failed on setup with &quot;Exception: Error&quot;">@pytest.fixture
    def make_error():
&gt;       raise Exception("Error")
E       Exception: Error

test_polarion.py:5: Exception</error>
      <properties>
        <property name="polarion-testcase-id" value="test_polarion.py::test_polarion" />
      </properties>
    </testcase>
  </testsuite>
</testsuites>