<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="3" failures="2" skipped="1" tests="9" time="0.043" timestamp="2023-03-30T14:05:45.617438" hostname="pbrezina.my"><testcase classname="tests.test_basic" name="test_success[1]" time="0.001" /><testcase classname="tests.test_basic" name="test_success[2]" time="0.000" /><testcase classname="tests.test_basic" name="test_failure_assert" time="0.000"><failure message="assert False">&gt;   ???
E   assert False

/home/pbrezina/workspace/pytest-output/tests/test_basic.py:67: AssertionError</failure></testcase><testcase classname="tests.test_basic" name="test_failure_exception" time="0.000"><failure message="ValueError: Error message">&gt;   ???
E   ValueError: Error message

/home/pbrezina/workspace/pytest-output/tests/test_basic.py:91: ValueError</failure></testcase><testcase classname="tests.test_basic" name="test_skipped" time="0.000"><skipped type="pytest.skip" message="Because.">/home/pbrezina/workspace/pytest-output/tests/test_basic.py:94: Because.</skipped></testcase><testcase classname="tests.test_basic" name="test_error_setup" time="0.000"><error message="failed on setup with &quot;ValueError: error&quot;">&gt;   ???
E   ValueError: error

/home/pbrezina/workspace/pytest-output/tests/test_basic.py:10: ValueError</error></testcase><testcase classname="tests.test_basic" name="test_error_teardown" time="0.000"><error message="failed on teardown with &quot;ValueError: error&quot;">&gt;   ???
E   ValueError: error

/home/pbrezina/workspace/pytest-output/tests/test_basic.py:16: ValueError</error></testcase><testcase classname="tests.test_basic" name="test_error_setup_teardown" time="0.000"><error message="failed on setup with &quot;ValueError: error&quot;">&gt;   ???
E   ValueError: error

/home/pbrezina/workspace/pytest-output/tests/test_basic.py:10: ValueError</error></testcase></testsuite></testsuites>